const {
  COOKIE_PARAMS,
  COOKIE_PARAMS_DEV,
  JWT_SECRET_DEV,
  DEFAULT_ALLOWED_METHODS,
  ALLOWED_CORS,
} = require('./constants');
const {
  DEFAULT_MESSAGE_RU,
  CONFLICT_CARD_MOVIE_RU,
  CONFLICT_USER_RU,
  FORBIDDEN_CARD_MOVIE_RU,
  NOT_FOUND_USER_RU,
  NOT_FOUND_CARD_MOVIE_RU,
  NOT_FOUND_DEFAULT_RU,
  LIMITTER_RU,
  AUTHORIZATION_REQUIRED_RU,
  AUTHORIZATION_WRONG_RU,
} = require('./errorMessages');
const mongoMessage = require('./mongoValidationMessage');
const validatorMessage = require('./validatorMessage');

module.exports = {
  DEFAULT_MESSAGE_RU,
  CONFLICT_CARD_MOVIE_RU,
  CONFLICT_USER_RU,
  FORBIDDEN_CARD_MOVIE_RU,
  NOT_FOUND_USER_RU,
  NOT_FOUND_CARD_MOVIE_RU,
  NOT_FOUND_DEFAULT_RU,
  LIMITTER_RU,
  AUTHORIZATION_REQUIRED_RU,
  AUTHORIZATION_WRONG_RU,
  mongoMessage,
  validatorMessage,
  COOKIE_PARAMS,
  COOKIE_PARAMS_DEV,
  JWT_SECRET_DEV,
  DEFAULT_ALLOWED_METHODS,
  ALLOWED_CORS,
};
